/* Red — the player sprite.
   Queen-of-the-block look: red hood up, gold hoop earrings, smirk,
   kangaroo-pocket hoodie, blue jeans with denim seams, chunky white sneakers.
   14x30, black outline for tiny-size readability. Overrides the engine placeholder. */
RH.registerSprite('red', {
  pal: {
    k: 0,   // black outline, eyes, soles
    r: 4,   // red hoodie
    R: 12,  // light red — hood/chest highlight, pocket
    s: 13,  // skin (pink)
    h: 6,   // brown bangs under the hood
    j: 1,   // blue jeans
    J: 9,   // light blue — denim seam / rolled cuffs
    w: 15,  // white — sneakers, drawstring tips
    y: 14,  // yellow — gold hoop earrings (her signature)
  },
  anchor: [7, 30],
  frames: {
    /* Standing: weight back, smirk on, hoops out. */
    stand: [
      '.....kkkk.....',
      '....krrrrk....',
      '...krrrrrrk...',
      '..krrRrrRrrk..',
      '..krhhhhhhrk..',
      '..krssssssrk..',
      '..krskssksrk..',
      '..krssssssrk..',
      '..krssskksrk..',
      '...krssssrk...',
      '..y.kwrrwk.y..',
      '.kkrrrrrrrrkk.',
      '.krrkrrrrkrrk.',
      '.krrkrRRrkrrk.',
      '.krrkrRRrkrrk.',
      '.krrkkkkkkrrk.',
      '.ksskRRRRkssk.',
      '..krrrrrrrrk..',
      '..kjjk..kjjk..',
      '..kjJk..kJjk..',
      '..kjjk..kjjk..',
      '..kjJk..kJjk..',
      '..kjjk..kjjk..',
      '..kjJk..kJjk..',
      '..kjjk..kjjk..',
      '..kjjk..kjjk..',
      '..kJJk..kJJk..',
      '..kwwk..kwwk..',
      '.kwwwk..kwwwk.',
      '.kkkkk..kkkkk.',
    ],
    /* Walk A: full stride, legs spread wide. */
    walk1: [
      '.....kkkk.....',
      '....krrrrk....',
      '...krrrrrrk...',
      '..krrRrrRrrk..',
      '..krhhhhhhrk..',
      '..krssssssrk..',
      '..krskssksrk..',
      '..krssssssrk..',
      '..krssskksrk..',
      '...krssssrk...',
      '..y.kwrrwk.y..',
      '.kkrrrrrrrrkk.',
      '.krrkrrrrkrrk.',
      '.krrkrRRrkrrk.',
      '.krrkrRRrkrrk.',
      '.krrkkkkkkrrk.',
      '.ksskRRRRkssk.',
      '..krrrrrrrrk..',
      '..kjjk..kjjk..',
      '..kjjk..kjjk..',
      '.kjjk....kjjk.',
      '.kjJk....kJjk.',
      '.kjjk....kjjk.',
      'kjjk......kjjk',
      'kjjk......kjjk',
      'kjJk......kJjk',
      'kjjk......kjjk',
      'kwwk......kwwk',
      'kwwwk....kwwwk',
      'kkkkk....kkkkk',
    ],
    /* Walk B: legs passing each other, feet together. */
    walk2: [
      '.....kkkk.....',
      '....krrrrk....',
      '...krrrrrrk...',
      '..krrRrrRrrk..',
      '..krhhhhhhrk..',
      '..krssssssrk..',
      '..krskssksrk..',
      '..krssssssrk..',
      '..krssskksrk..',
      '...krssssrk...',
      '..y.kwrrwk.y..',
      '.kkrrrrrrrrkk.',
      '.krrkrrrrkrrk.',
      '.krrkrRRrkrrk.',
      '.krrkrRRrkrrk.',
      '.krrkkkkkkrrk.',
      '.ksskRRRRkssk.',
      '..krrrrrrrrk..',
      '..kjjk..kjjk..',
      '...kjjkkjjk...',
      '...kjjkkjjk...',
      '....kjjjjk....',
      '....kjJJjk....',
      '....kjjjjk....',
      '....kjjjjk....',
      '....kjjjjk....',
      '....kJjjJk....',
      '....kwwwwk....',
      '...kwwwwwwk...',
      '...kkkkkkkk...',
    ],
  },
});
